// js/lang.js
const translations = {
  en: {
    home: "Home",
    about: "About",
    skills: "Skills",
    projects: "Projects",
    contact: "Contact",
    hero_greeting: "Hello, I'm",
    hero_subtitle: "Full Stack Developer",
    hero_description: "I create beautiful and functional web applications",
    view_work: "View My Work",
    get_in_touch: "Get In Touch",
    about_title: "About Me",
    about_description: "I am a passionate Full Stack Developer with experience in creating web applications using modern technologies. I love solving complex problems and learning new technologies.",
    contact_title: "Get In Touch",
    send_message: "Send Message",
    years_Experience: "Years Experience",
    projects_Completed: "Projects Completed",
    happy_Clients: "Happy Clients",
    work_together: "Let's work together",
    always_interested: "I'm always interested in hearing about new projects and opportunities.",
    my_skills: "My Skills",
    my_projects: "My Projects"
  },
  th: {
    home: "หน้าหลัก",
    about: "เกี่ยวกับ",
    skills: "ทักษะ",
    projects: "ผลงาน",
    contact: "ติดต่อ",
    hero_greeting: "สวัสดี, ผมชื่อ",
    hero_subtitle: "นักพัฒนาเว็บ Full Stack",
    hero_description: "ผมสร้างเว็บแอปที่สวยและใช้งานได้จริง",
    view_work: "ดูผลงาน",
    get_in_touch: "ติดต่อผม",
    about_title: "เกี่ยวกับผม",
    about_description: "ฉันเป็นนักพัฒนา Full Stack ที่หลงใหลและมีประสบการณ์ในการสร้างเว็บแอปพลิเคชันโดยใช้เทคโนโลยีสมัยใหม่ ฉันรักการแก้ปัญหาที่ซับซ้อนและเรียนรู้เทคโนโลยีใหม่ๆ",
    contact_title: "ติดต่อผม",
    send_message: "ส่งข้อความ",
    years_experience: "ประสบการณ์หลายปี",
    projects_completed: "โครงการที่เสร็จสมบูรณ์",
    happy_clients: "ลูกค้าที่มีความสุข",
    work_together: "มาทำงานร่วมกัน",
    always_interested: "ฉันสนใจที่จะได้ยินเกี่ยวกับโครงการและโอกาสใหม่ๆ อยู่เสมอ",
    my_skills: "ทักษะของฉัน",
    my_projects: "โครงการของฉัน"
  },
};
